### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by varunon9** [abhik-setia/Techspardha-Website#13]
Great work (techspardha.org) and congrats for making it open source. A simple thing which beginners ignore is putting a  README file. A great README file helps your project to stand out from the sea of open-source software on GitHub. Additionally It helps in SEO and make your profile stronger. 
You can put some info about techspardha, website installation/deployment instructions, how to contribute section etc. This will help new developers (probably your juniors) in getting started.

**Comment by abhik-setia** [comment]
Sure, sir. We will add it. Thank you for your feedback :)
